# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inner', '0005_inner_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64)),
                ('content', models.CharField(blank=True, max_length=256)),
                ('thumbnail', models.CharField(blank=True, max_length=256)),
                ('url', models.CharField(blank=True, max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('inner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_slider', to='inner.Inner')),
            ],
        ),
    ]
