# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_recommend_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='email',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
