# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inner', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inner',
            unique_together=set([('name', 'category')]),
        ),
    ]
