# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outer', '0002_auto_20170623_0048'),
        ('inner', '0002_auto_20170623_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='inner',
            name='outer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inner', to='outer.Outer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='inner',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='inner',
            name='category',
        ),
    ]
