# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outer', '0002_auto_20170623_0048'),
        ('inner', '0003_auto_20170623_1055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inner',
            unique_together=set([('name', 'outer')]),
        ),
    ]
