# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('real_id', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('thumbnails', models.URLField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('inner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inner.Inner')),
            ],
        ),
    ]
