# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='last_update_time',
            field=models.DateTimeField(blank=True, default='2017-06-12T00:08:54.000Z'),
            preserve_default=False,
        ),
    ]
