# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20170621_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='real_id',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
