# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_remove_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='create_time',
            field=models.DateTimeField(),
        ),
    ]
