# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0006_auto_20170622_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='subscriber',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
