# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_playlist_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['subscriber']},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
