# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0008_auto_20170623_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='thumbnails',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
