# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_auto_20170623_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('hot', 'hot'), ('new', 'new')], default='hot', max_length=10),
        ),
    ]
