# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0010_playlist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='submit',
            field=models.CharField(choices=[('user', 'user'), ('maintainer', 'maintainer')], default='maintainer', max_length=10),
        ),
    ]
