# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0012_playlist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='submit',
        ),
        migrations.AddField(
            model_name='playlist',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
