# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outer',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
