# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inner', '0005_inner_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quora', models.SmallIntegerField(default=0)),
                ('blog', models.SmallIntegerField(default=0)),
                ('forums', models.SmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('inner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered', to='inner.Inner')),
            ],
        ),
    ]
