# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='name',
            field=models.CharField(default='yoo', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
